### ISSUE TITLE
LXC: Get ENOS running in container

### ISSUE THREAD

**Issue by jmacauley** [esnet/enos#87]
Get an ENOS image running in an LXC on the testbed.

**Comment by bmah888** [comment]
The dev instance of ENOS I have been using was running on the bare-metal host aofa-tbn-1.  This instance needs to be moved and/or recreated on an LXC.

This issue is for making that happen.  Note that this involves several steps:

Create and configure an LXC.

Deploy ENOS with ODL / Karaf integration into the LXC.

Reconfigure several Corsa hardware switches at DENV, ATLA, STAR, and AOFA to look to this LXC as as a controller.

Either recreate OSCARS circuits for connectivity between the hardware switches or complete the work for #44.

Create some set of LXCs as site hosts, hosted on denv-tbn-1, atla-tbn-1, star-tbn-4, aofa-tbn-1.

Confirm site descriptors for these sites..

Re-test MP-VPN application in this environment.

**Comment by bmah888** [comment]
Increasing the effort estimate due to the amount of time spent setting up a usable environment on the SDN testbed.  This includes creating provisioning various LXCs and OVS instances and making sure they work together correctly, writing documentation for INF to use, etc.

At this point, we have set up a two-node MP-VPN instance between DENV and ATLA.  A little more testing is required (in particularly with more sites) to declare victory.

**Comment by bmah888** [comment]
This has been tested with a three-site MP-VPN with the control plane and all data plane hosts implemented as Proxmox LXCs, with connectivity provided by epipes (#44).
